### ISSUE TITLE
Cannot Download All Tracks

### ISSUE THREAD

**Issue by Gui91300** [Fraeio/Music-Module#6] opened 2021-03-23 17:20 UTC
Hello, I tried to download the All tracks File and I can not do that.

The web browser returns Unable to download - Error from Server.

But I can download each songs individually. Will take ages to do that ...

If you can see what is the problem and, if possible, correct it, it would be great ;)

Cheers

**Comment by LovBlueFox** [comment] 2021-03-25 09:01
Thanks for the report, The issue is now fixed

**Closed as completed by LovBlueFox** 2021-03-25 09:01 UTC
Labels: bug
